import { UserData } from "./type";

export const users: UserData[] = [
  {
    id: 1,
    name: "Ahmed Hassan",
    email: "ahmed.hassan@mail.com",
    phone: "+201012345678",
    address: "Cairo, Egypt",
    isActive: true,
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah.johnson@mail.com",
    phone: "+14155550123",
    address: "New York, USA",
    isActive: false,
  },
  {
    id: 3,
    name: "Omar Khaled",
    email: "omar.khaled@mail.com",
    phone: "+201098765432",
    address: "Giza, Egypt",
    isActive: true,
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily.davis@mail.com",
    phone: "+447911123456",
    address: "London, UK",
    isActive: true,
  },
  {
    id: 5,
    name: "Mohamed Ali",
    email: "mohamed.ali@mail.com",
    phone: "+201155667788",
    address: "Alexandria, Egypt",
    isActive: true,
  },
  {
    id: 6,
    name: "Daniel Wilson",
    email: "daniel.wilson@mail.com",
    phone: "+12125556789",
    address: "Chicago, USA",
    isActive: false,
  },
  {
    id: 7,
    name: "Mariam Adel",
    email: "mariam.adel@mail.com",
    phone: "+201122334455",
    address: "Qina, Egypt",
    isActive: true,
  },
  {
    id: 8,
    name: "James Anderson",
    email: "james.anderson@mail.com",
    phone: "+61412345678",
    address: "Sydney, Australia",
    isActive: true,
  },
  {
    id: 9,
    name: "Nour Ibrahim",
    email: "nour.ibrahim@mail.com",
    phone: "+201100223344",
    address: "Mansoura, Egypt",
    isActive: true,
  },
  {
    id: 10,
    name: "Sophia Martinez",
    email: "sophia.martinez@mail.com",
    phone: "+34911223344",
    address: "Madrid, Spain",
    isActive: true,
  },
  {
    id: 11,
    name: "Youssef Samir",
    email: "youssef.samir@mail.com",
    phone: "+201066778899",
    address: "Luxor, Egypt",
    isActive: true,
  },
  {
    id: 12,
    name: "Michael Brown",
    email: "michael.brown@mail.com",
    phone: "+493012345678",
    address: "Berlin, Germany",
    isActive: true,
  },
  {
    id: 13,
    name: "Aya Mahmoud",
    email: "aya.mahmoud@mail.com",
    phone: "+201011223344",
    address: "Aswan, Egypt",
    isActive: true,
  },
  {
    id: 14,
    name: "Lucas Taylor",
    email: "lucas.taylor@mail.com",
    phone: "+33142345678",
    address: "Paris, France",
    isActive: true,
  },
  {
    id: 15,
    name: "Hana Mostafa",
    email: "hana.mostafa@mail.com",
    phone: "+201055667788",
    address: "Port Said, Egypt",
    isActive: false,
  },
];